/**
 * Starting points for an automation.
 *
 * The blank editor is where a non-technical buyer stalls. They understand what
 * they want to happen; they do not know what to type in a DM, and a bad first
 * message produces a bad first result, which is when people ask for refunds.
 *
 * Every template here is a complete, sendable automation — keyword, message,
 * button wording, and where relevant the public reply and the follow gate. They
 * are prefilled into the editor rather than saved directly, so the creator
 * always reads and edits before anything goes live.
 *
 * The copy is deliberately plain. It is written to be sent by a person to a
 * person, so no marketing voice, no exclamation stacking, and `{username}` used
 * once at most — a message that greets you twice reads as a machine.
 */

export type TemplateCategory =
  | "Link in bio"
  | "Lead magnet"
  | "Selling"
  | "Growing"
  | "Stories"
  | "Service business";

export interface Template {
  id: string;
  category: TemplateCategory;
  name: string;
  /** One line, shown on the card. Says when to reach for it. */
  blurb: string;
  trigger: "COMMENT" | "DM" | "STORY_REPLY" | "STORY_MENTION";
  keywords: string;
  message: string;
  buttonLabel?: string;
  /** One variant per line. Only meaningful for comment triggers. */
  publicReplies?: string;
  matchAny?: boolean;
  requireFollow?: boolean;
  collectEmail?: boolean;
  emailPrompt?: string;
  emailThanks?: string;
  followUp?: string;
  followUpDelayMins?: number;
  /** Days. Matches how long the thing it is attached to lives. */
  expiresInDays?: number;
}

export const TEMPLATES: Template[] = [
  // --- Link in bio ---------------------------------------------------------
  {
    id: "link-in-bio",
    category: "Link in bio",
    name: "Send my link",
    blurb: "The basic one. Someone comments a word, they get your link.",
    trigger: "COMMENT",
    keywords: "LINK",
    message: "Hey {username}, here's the link you asked for.",
    buttonLabel: "Open the link",
    publicReplies: "Sent!\nCheck your DMs\nOn its way",
  },
  {
    id: "shop-link",
    category: "Link in bio",
    name: "Send my shop",
    blurb: "For a product post. Comment SHOP, get the store link.",
    trigger: "COMMENT",
    keywords: "SHOP, BUY, WHERE",
    message: "Here's where you can get it, {username}.",
    buttonLabel: "Shop now",
    publicReplies: "Just sent it\nDMed you the link\nCheck your messages",
  },
  {
    id: "recipe-link",
    category: "Link in bio",
    name: "Send the recipe",
    blurb: "Food posts. Comment RECIPE, get the full method.",
    trigger: "COMMENT",
    keywords: "RECIPE",
    message: "Here's the full recipe, {username}. Tag me if you make it.",
    buttonLabel: "Get the recipe",
    publicReplies: "Sent it over\nIn your DMs\nJust sent",
  },
  {
    id: "song-link",
    category: "Link in bio",
    name: "Send the song or playlist",
    blurb: "Music, edits, reels using your audio.",
    trigger: "COMMENT",
    keywords: "SONG, TRACK, AUDIO",
    message: "Here's the track, {username}.",
    buttonLabel: "Listen",
    publicReplies: "Sent\nCheck your DMs\nDMed you",
  },
  {
    id: "gear-list",
    category: "Link in bio",
    name: "Send my gear list",
    blurb: "For the constant \"what camera do you use\" question.",
    trigger: "COMMENT",
    keywords: "GEAR, SETUP, CAMERA",
    message: "Everything I use is on this page, {username}.",
    buttonLabel: "See the list",
    publicReplies: "Sent the list\nDMed it to you\nCheck your messages",
  },
  {
    id: "blog-post",
    category: "Link in bio",
    name: "Send the full article",
    blurb: "When the caption is a summary and the article is elsewhere.",
    trigger: "COMMENT",
    keywords: "READ, ARTICLE, BLOG",
    message: "Here's the full write-up, {username}. It's a five-minute read.",
    buttonLabel: "Read it",
  },
  {
    id: "video-link",
    category: "Link in bio",
    name: "Send the long version",
    blurb: "Point reel viewers at the full YouTube video.",
    trigger: "COMMENT",
    keywords: "FULL, VIDEO, YOUTUBE",
    message: "The full version is here, {username}.",
    buttonLabel: "Watch it",
  },
  {
    id: "dm-link",
    category: "Link in bio",
    name: "Link on DM",
    blurb: "For when you say \"DM me LINK\" in a story or caption.",
    trigger: "DM",
    keywords: "LINK",
    message: "Here you go, {username}.",
    buttonLabel: "Open the link",
  },

  // --- Lead magnet ---------------------------------------------------------
  {
    id: "free-guide-email",
    category: "Lead magnet",
    name: "Free guide for an email",
    blurb: "Asks for their email, then sends the guide. Builds your list.",
    trigger: "COMMENT",
    keywords: "GUIDE",
    message: "Hey {username}, happy to send the guide over.",
    buttonLabel: "Download the guide",
    collectEmail: true,
    emailPrompt: "What's the best email to send it to?",
    emailThanks: "Got it. Here's your guide.",
    publicReplies: "Sent!\nCheck your DMs\nJust sent it over",
  },
  {
    id: "checklist-email",
    category: "Lead magnet",
    name: "Checklist for an email",
    blurb: "Same exchange, for a one-page checklist.",
    trigger: "COMMENT",
    keywords: "CHECKLIST",
    message: "I'll send the checklist right over, {username}.",
    buttonLabel: "Get the checklist",
    collectEmail: true,
    emailPrompt: "Drop your email and I'll send it.",
    emailThanks: "Here it is. Enjoy.",
  },
  {
    id: "template-pack-email",
    category: "Lead magnet",
    name: "Template pack for an email",
    blurb: "Canva templates, notion setups, presets.",
    trigger: "COMMENT",
    keywords: "TEMPLATES, PACK",
    message: "The pack is ready for you, {username}.",
    buttonLabel: "Get the pack",
    collectEmail: true,
    emailPrompt: "What email should I send it to?",
    emailThanks: "Sent. Here's your download.",
  },
  {
    id: "free-guide-nogate",
    category: "Lead magnet",
    name: "Free guide, no email",
    blurb: "Straight to the download. Fewer signups, more goodwill.",
    trigger: "COMMENT",
    keywords: "GUIDE",
    message: "Here's the guide, {username}. No signup needed.",
    buttonLabel: "Download it",
    publicReplies: "Sent\nIn your DMs\nJust sent it",
  },
  {
    id: "waitlist",
    category: "Lead magnet",
    name: "Join the waitlist",
    blurb: "Before a launch. Collects emails you can sell to later.",
    trigger: "COMMENT",
    keywords: "WAITLIST, EARLY",
    message: "I'll put you on the early list, {username}.",
    buttonLabel: "See what's coming",
    collectEmail: true,
    emailPrompt: "What email should I use for the waitlist?",
    emailThanks: "You're on the list. You'll hear first.",
  },
  {
    id: "newsletter",
    category: "Lead magnet",
    name: "Newsletter signup",
    blurb: "Turns a good post into subscribers.",
    trigger: "COMMENT",
    keywords: "SUBSCRIBE, NEWSLETTER",
    message: "I write one email a week, {username}. Nothing else.",
    collectEmail: true,
    emailPrompt: "Which email should I add?",
    emailThanks: "Added. First one arrives Sunday.",
  },
  {
    id: "webinar",
    category: "Lead magnet",
    name: "Free workshop seat",
    blurb: "Live session or workshop registration.",
    trigger: "COMMENT",
    keywords: "WORKSHOP, CLASS",
    message: "There are still seats, {username}.",
    buttonLabel: "Save my seat",
    collectEmail: true,
    emailPrompt: "What email should the joining link go to?",
    emailThanks: "You're registered. Details are in your inbox.",
  },
  {
    id: "dm-freebie",
    category: "Lead magnet",
    name: "Freebie on DM",
    blurb: "For \"DM me FREE\" in a story or bio.",
    trigger: "DM",
    keywords: "FREE, FREEBIE",
    message: "Sending it now, {username}.",
    collectEmail: true,
    emailPrompt: "What's your email?",
    emailThanks: "Here you go.",
    buttonLabel: "Download",
  },

  // --- Selling -------------------------------------------------------------
  {
    id: "price-list",
    category: "Selling",
    name: "Send the price list",
    blurb: "Stops you typing prices out fifty times a week.",
    trigger: "COMMENT",
    keywords: "PRICE, PRICING, COST",
    message: "Here's everything with prices, {username}.",
    buttonLabel: "See prices",
    publicReplies: "Sent the prices\nDMed you\nCheck your messages",
  },
  {
    id: "price-dm",
    category: "Selling",
    name: "Price list on DM",
    blurb: "Same, for people who message instead of commenting.",
    trigger: "DM",
    keywords: "PRICE, PRICING, HOW MUCH, COST",
    message: "Here's the full price list, {username}.",
    buttonLabel: "See prices",
  },
  {
    id: "discount-code",
    category: "Selling",
    name: "Send a discount code",
    blurb: "Comment for a code. Good for launches.",
    trigger: "COMMENT",
    keywords: "CODE, DISCOUNT",
    message: "Your code is INSTA10 — 10% off, {username}.",
    buttonLabel: "Use it now",
    publicReplies: "Code sent\nCheck your DMs\nJust sent it",
    expiresInDays: 7,
  },
  {
    id: "restock",
    category: "Selling",
    name: "Tell me when it's back",
    blurb: "Sold out post. Collects emails for the restock.",
    trigger: "COMMENT",
    keywords: "RESTOCK, BACK",
    message: "I'll let you know the moment it's back, {username}.",
    collectEmail: true,
    emailPrompt: "What email should I notify?",
    emailThanks: "Done. You'll be first to know.",
  },
  {
    id: "course-info",
    category: "Selling",
    name: "Course details",
    blurb: "Full curriculum and price for a course.",
    trigger: "COMMENT",
    keywords: "COURSE, ENROL, ENROLL",
    message: "Everything about the course is here, {username} — modules, price, and what you get.",
    buttonLabel: "See the course",
  },
  {
    id: "coaching",
    category: "Selling",
    name: "Coaching enquiry",
    blurb: "Sends your application form.",
    trigger: "COMMENT",
    keywords: "COACHING, MENTOR, 1:1",
    message: "I take a few clients at a time, {username}. Here's the form.",
    buttonLabel: "Apply",
    collectEmail: true,
    emailPrompt: "What's your email so I can follow up?",
    emailThanks: "Thanks. Here's the application.",
  },
  {
    id: "affiliate",
    category: "Selling",
    name: "Affiliate product link",
    blurb: "Sends your tracked link for a product you recommend.",
    trigger: "COMMENT",
    keywords: "LINK, WHERE",
    message: "Here's the one I use, {username}.",
    buttonLabel: "Take a look",
  },
  {
    id: "preset-pack",
    category: "Selling",
    name: "Presets or filters",
    blurb: "Photo and video creators selling a pack.",
    trigger: "COMMENT",
    keywords: "PRESET, PRESETS, FILTER",
    message: "The pack is here, {username} — works on both mobile and desktop.",
    buttonLabel: "Get the presets",
  },
  {
    id: "abandoned-followup",
    category: "Selling",
    name: "Link now, nudge later",
    blurb: "Sends the link, then a reminder two hours on.",
    trigger: "COMMENT",
    keywords: "BUY, SHOP",
    message: "Here it is, {username}.",
    buttonLabel: "Have a look",
    followUp: "Still thinking about it? Happy to answer anything.",
    followUpDelayMins: 120,
  },

  // --- Growing -------------------------------------------------------------
  {
    id: "follow-gate-guide",
    category: "Growing",
    name: "Follow first, then the guide",
    blurb: "Grows followers. Costs you some clicks — watch your rate.",
    trigger: "COMMENT",
    keywords: "GUIDE",
    message: "Here's the guide, {username}.",
    buttonLabel: "Download",
    requireFollow: true,
    publicReplies: "Sent!\nCheck your DMs\nJust sent it",
  },
  {
    id: "giveaway",
    category: "Growing",
    name: "Giveaway entry",
    blurb: "Confirms every entry. Set it to stop when the giveaway ends.",
    trigger: "COMMENT",
    keywords: "ENTER, IN, ME",
    message: "You're entered, {username}. Winner announced Friday.",
    matchAny: true,
    publicReplies: "You're in\nEntered\nGot you",
    expiresInDays: 7,
  },
  {
    id: "giveaway-follow",
    category: "Growing",
    name: "Giveaway, follow required",
    blurb: "Same, but they must follow to be entered.",
    trigger: "COMMENT",
    keywords: "ENTER, IN",
    message: "You're entered, {username}. Good luck.",
    matchAny: true,
    requireFollow: true,
    expiresInDays: 7,
  },
  {
    id: "reply-everyone",
    category: "Growing",
    name: "Reply to every comment",
    blurb: "Every commenter gets a DM. Good for a post that took off.",
    trigger: "COMMENT",
    keywords: "",
    message: "Thanks for commenting, {username}. Here's something you might like.",
    matchAny: true,
    buttonLabel: "Take a look",
  },
  {
    id: "thank-mentions",
    category: "Growing",
    name: "Thank story mentions",
    blurb: "Someone tags you in their story, they get a thank you.",
    trigger: "STORY_MENTION",
    keywords: "",
    message: "Thanks for the tag, {username}. Really appreciate it.",
  },
  {
    id: "welcome-dm",
    category: "Growing",
    name: "Welcome anyone who messages",
    blurb: "A friendly first reply to any DM. Use as your default reply.",
    trigger: "DM",
    keywords: "",
    matchAny: true,
    message: "Hey {username}, thanks for the message. I read everything and reply as soon as I can.",
  },
  {
    id: "community",
    category: "Growing",
    name: "Invite to the community",
    blurb: "Discord, WhatsApp group, Telegram.",
    trigger: "COMMENT",
    keywords: "JOIN, COMMUNITY, GROUP",
    message: "Here's the invite, {username}. It's free and fairly quiet.",
    buttonLabel: "Join",
  },
  {
    id: "collab",
    category: "Growing",
    name: "Collaboration enquiries",
    blurb: "Routes brand and collab DMs to your rate card.",
    trigger: "DM",
    keywords: "COLLAB, BRAND, PARTNERSHIP, PR",
    message: "Thanks for reaching out. My rates and audience numbers are here.",
    buttonLabel: "Media kit",
    collectEmail: true,
    emailPrompt: "What's the best email for your team?",
    emailThanks: "Thanks. Here's the media kit.",
  },

  // --- Stories -------------------------------------------------------------
  {
    id: "story-link",
    category: "Stories",
    name: "Story reply gets the link",
    blurb: "Put \"reply LINK\" on a story. Set it to stop in a day.",
    trigger: "STORY_REPLY",
    keywords: "LINK",
    message: "Here's the link, {username}.",
    buttonLabel: "Open it",
    expiresInDays: 1,
  },
  {
    id: "story-guide",
    category: "Stories",
    name: "Story reply gets the guide",
    blurb: "Lead magnet from a story instead of a post.",
    trigger: "STORY_REPLY",
    keywords: "GUIDE",
    message: "Sending it now, {username}.",
    buttonLabel: "Download",
    collectEmail: true,
    emailPrompt: "What email should I send it to?",
    emailThanks: "Here you go.",
    expiresInDays: 1,
  },
  {
    id: "story-price",
    category: "Stories",
    name: "Story reply gets prices",
    blurb: "Product story. Reply PRICE for the list.",
    trigger: "STORY_REPLY",
    keywords: "PRICE, COST",
    message: "Here's the price list, {username}.",
    buttonLabel: "See prices",
    expiresInDays: 1,
  },
  {
    id: "story-two-offers",
    category: "Stories",
    name: "Two stories, two offers",
    blurb: "Use one keyword per story. Make a second copy for the other.",
    trigger: "STORY_REPLY",
    keywords: "GUIDE",
    message: "Here's the guide, {username}.",
    buttonLabel: "Download",
    expiresInDays: 1,
  },
  {
    id: "story-poll",
    category: "Stories",
    name: "Answer story questions",
    blurb: "Anyone who replies to a story gets a set answer.",
    trigger: "STORY_REPLY",
    keywords: "",
    matchAny: true,
    message: "Thanks for replying, {username}. Here's what I use.",
    buttonLabel: "See it",
    expiresInDays: 1,
  },

  // --- Service business ----------------------------------------------------
  {
    id: "booking",
    category: "Service business",
    name: "Send my booking link",
    blurb: "Salons, clinics, trainers, photographers.",
    trigger: "COMMENT",
    keywords: "BOOK, BOOKING, APPOINTMENT",
    message: "You can book a slot here, {username}.",
    buttonLabel: "Book a time",
    publicReplies: "Sent the booking link\nDMed you\nCheck your messages",
  },
  {
    id: "booking-dm",
    category: "Service business",
    name: "Booking link on DM",
    blurb: "Same, for people who message rather than comment.",
    trigger: "DM",
    keywords: "BOOK, APPOINTMENT, SLOT, AVAILABLE",
    message: "Here's my calendar, {username} — pick anything that's free.",
    buttonLabel: "Book a time",
  },
  {
    id: "menu",
    category: "Service business",
    name: "Send the menu",
    blurb: "Cafés and restaurants.",
    trigger: "COMMENT",
    keywords: "MENU",
    message: "Here's the menu, {username}.",
    buttonLabel: "See the menu",
  },
  {
    id: "location-hours",
    category: "Service business",
    name: "Where are you and when",
    blurb: "Answers the address-and-opening-hours question.",
    trigger: "DM",
    keywords: "OPEN, HOURS, WHERE, ADDRESS, LOCATION",
    message: "We're open 9am to 7pm, Tuesday to Sunday. Directions below.",
    buttonLabel: "Get directions",
  },
  {
    id: "quote",
    category: "Service business",
    name: "Request a quote",
    blurb: "Trades and freelancers. Captures the email with it.",
    trigger: "DM",
    keywords: "QUOTE, ESTIMATE, HOW MUCH",
    message: "Happy to quote. Tell me roughly what you need and I'll come back with a number.",
    collectEmail: true,
    emailPrompt: "What email should I send the quote to?",
    emailThanks: "Thanks. I'll be in touch within a day.",
  },
  {
    id: "portfolio",
    category: "Service business",
    name: "Send my portfolio",
    blurb: "Designers, photographers, editors.",
    trigger: "DM",
    keywords: "PORTFOLIO, WORK, EXAMPLES",
    message: "Here's a selection of recent work, {username}.",
    buttonLabel: "View portfolio",
  },
  {
    id: "waiting-list-service",
    category: "Service business",
    name: "Fully booked, take the list",
    blurb: "For when you have no slots but want the lead.",
    trigger: "DM",
    keywords: "BOOK, SLOT, AVAILABLE",
    message: "I'm fully booked this month, but I can let you know the moment something opens.",
    collectEmail: true,
    emailPrompt: "What email should I use?",
    emailThanks: "You're on the list. I'll be in touch.",
  },
];

export function templateById(id: string): Template | undefined {
  return TEMPLATES.find((t) => t.id === id);
}

export const CATEGORIES: TemplateCategory[] = [
  "Link in bio",
  "Lead magnet",
  "Selling",
  "Growing",
  "Stories",
  "Service business",
];
